### PR TITLE
Add MIT License to project

### PR DESCRIPTION
**Pull request by igeligel**
**What kind of change does this PR introduce?**

- Adding the missing license, the repository's readme said it would be MIT licensed but i have not found any license so i added it

### CODE REVIEW

**Comment by octref** [comment]
Thanks! Maybe change this line to be the same as vetur? https://github.com/vuejs/vetur/blob/master/LICENSE#L3

**Comment by igeligel** [comment]
You really think its better to just write the current year?

For example the official Vue.js license also holds the current year inside ([reference](https://github.com/vuejs/vue/blob/dev/LICENSE#L3)).

**Comment by octref** [comment]
Alright I'll update Vetur's license. I'm a license noob sorry 😝

**Comment by igeligel** [comment]
Haha no problem. You are still a fantastic programmer considering vetur, making Vue.js development awesome 💯 👍

**Pull request merged**
